In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


In [ ]:
# Load the dataset
url = "/content/drive/MyDrive/healthcare_dataset.csv"
df = pd.read_csv(url)

# Display the first few rows of the dataset
print(df.head())


            Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31   
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22   
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18   
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19   

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross   
1   Samantha Davies                     Kim Inc           Medicare   
2  Tiffany Mitchell                    Cook PLC              Aetna   
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare   
4    Kathleen Hanna                 White-White              Aetna   

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306    

In [ ]:
import pandas as pd

# Assuming your data is in a DataFrame called df
columns_to_drop = ['Name', 'Date of Admission', 'Doctor', 'Hospital',
                   'Insurance Provider', 'Room Number', 'Discharge Date']

df = df.drop(columns=columns_to_drop)


In [ ]:
print(df.head())


   Age  Gender Blood Type Medical Condition  Billing Amount Admission Type  \
0   30    Male         B-            Cancer    18856.281306         Urgent   
1   62    Male         A+           Obesity    33643.327287      Emergency   
2   76  Female         A-           Obesity    27955.096079      Emergency   
3   28  Female         O+          Diabetes    37909.782410       Elective   
4   43  Female        AB+            Cancer    14238.317814         Urgent   

    Medication  Test Results  
0  Paracetamol        Normal  
1    Ibuprofen  Inconclusive  
2      Aspirin        Normal  
3    Ibuprofen      Abnormal  
4   Penicillin      Abnormal  


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import pandas as pd

# Load your dataset (assuming you have a DataFrame called df)
# df = pd.read_csv('your_dataset.csv')  # Uncomment if you are reading from a file

# Splitting features and target
X = df.drop('Test Results', axis=1)
y = df['Test Results']

# Encode the target variable (y) if it's categorical
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# One-hot encoding for categorical variables
categorical_cols = X.select_dtypes(include=['object']).columns  # Select categorical columns
onehot_encoder = OneHotEncoder(sparse_output=False, drop='first')  # Drop first to avoid multicollinearity
X_encoded = pd.DataFrame(onehot_encoder.fit_transform(X[categorical_cols]))

# Rename columns after encoding
X_encoded.columns = onehot_encoder.get_feature_names_out(categorical_cols)

# Drop original categorical columns and concatenate encoded columns
X = X.drop(categorical_cols, axis=1)
X = pd.concat([X, X_encoded], axis=1)

# Scale numerical features
scaler = StandardScaler()  # You can also use MinMaxScaler() if preferred
numerical_cols = X.select_dtypes(include=['float64', 'int64']).columns  # Select numerical columns
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])  # Standardize numerical features

# Splitting the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC()
}

# Evaluate each model
for model_name, model in models.items():
    # Fit the model
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Generate confusion matrix and classification report
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)

    # Display results
    print(f"Model: {model_name}")
    print(f"Accuracy: {accuracy:.2f}")
    print("Confusion Matrix:\n", conf_matrix)
    print("Classification Report:\n", class_report)
    print("=" * 50)


Model: Logistic Regression
Accuracy: 0.34
Confusion Matrix:
 [[1676  961 1117]
 [1551  929 1137]
 [1591  938 1200]]
Classification Report:
               precision    recall  f1-score   support

    Abnormal       0.35      0.45      0.39      3754
Inconclusive       0.33      0.26      0.29      3617
      Normal       0.35      0.32      0.33      3729

    accuracy                           0.34     11100
   macro avg       0.34      0.34      0.34     11100
weighted avg       0.34      0.34      0.34     11100

Model: Decision Tree
Accuracy: 0.40
Confusion Matrix:
 [[1476 1111 1167]
 [1047 1431 1139]
 [1148 1057 1524]]
Classification Report:
               precision    recall  f1-score   support

    Abnormal       0.40      0.39      0.40      3754
Inconclusive       0.40      0.40      0.40      3617
      Normal       0.40      0.41      0.40      3729

    accuracy                           0.40     11100
   macro avg       0.40      0.40      0.40     11100
weighted avg       

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE

# Define the RandomForestClassifier model
rf_clf = RandomForestClassifier()

# Apply Recursive Feature Elimination (RFE) with RandomForestClassifier
rfe = RFE(estimator=rf_clf, n_features_to_select=10)
X_rfe = rfe.fit_transform(X, y_encoded)

# Fit the model to the selected features
rf_clf.fit(X_rfe, y_encoded)


RandomForestClassifier()

In [ ]:
importances = rf_clf.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
print(feature_importance_df)


ValueError: All arrays must be of the same length

In [ ]:
import numpy as np

def add_laplace_noise(data, epsilon):
    """
    Add Laplace noise to the predictions for differential privacy.
    Epsilon is the privacy budget parameter controlling the noise level.
    """
    noise = np.random.laplace(0, 1/epsilon, size=data.shape)
    noisy_data = data + noise
    return np.round(noisy_data)

epsilon = 0.1  # Privacy budget
y_pred_noisy = add_laplace_noise(y_pred, epsilon)

# Evaluate the model with noisy predictions
accuracy_noisy = accuracy_score(y_test, y_pred_noisy)
conf_matrix_noisy = confusion_matrix(y_test, y_pred_noisy)
class_report_noisy = classification_report(y_test, y_pred_noisy)

# Output the results
print(f"Accuracy with Differential Privacy: {accuracy_noisy * 100:.2f}%")
print("Confusion Matrix with Differential Privacy:")
print(conf_matrix_noisy)
print("Classification Report with Differential Privacy:")
print(class_report_noisy)

In [ ]:

epsilon = 0.4  # Privacy budget
y_pred_noisy = add_laplace_noise(y_pred, epsilon)

# Evaluate the model with noisy predictions
accuracy_noisy = accuracy_score(y_test, y_pred_noisy)
conf_matrix_noisy = confusion_matrix(y_test, y_pred_noisy)
class_report_noisy = classification_report(y_test, y_pred_noisy)

# Output the results
print(f"Accuracy with Differential Privacy: {accuracy_noisy * 100:.2f}%")
print("Confusion Matrix with Differential Privacy:")
print(conf_matrix_noisy)
print("Classification Report with Differential Privacy:")
print(class_report_noisy)

In [ ]:
import pandas as pd

# Assuming your data is in a DataFrame called df
columns_to_drop = ['Name', 'Date of Admission', 'Doctor', 'Hospital',
                   'Insurance Provider', 'Room Number', 'Discharge Date']

df = df.drop(columns=columns_to_drop)


In [ ]:
df.columns

In [ ]:
# Required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import SelectFromModel

# Load your dataset (assuming you have a DataFrame called df)
# df = pd.read_csv('your_dataset.csv')  # Uncomment if you are reading from a file

# Splitting features and target
X = df.drop('Test Results', axis=1)
y = df['Test Results']

# One-hot encoding for categorical variables
categorical_cols = X.select_dtypes(include=['object']).columns  # Select categorical columns
onehot_encoder = OneHotEncoder(sparse=False, drop='first')  # Drop first to avoid multicollinearity
X_encoded = pd.DataFrame(onehot_encoder.fit_transform(X[categorical_cols]))

# Rename columns after encoding
X_encoded.columns = onehot_encoder.get_feature_names_out(categorical_cols)

# Drop original categorical columns and concatenate encoded columns
X = X.drop(categorical_cols, axis=1)



In [ ]:
#X_encoded.head(50)

In [ ]:
X = pd.concat([X.reset_index(drop=True), X_encoded.reset_index(drop=True)], axis=1)

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train Random Forest model for feature selection
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)

# Select important features
selector = SelectFromModel(rfc, prefit=True)
X_train_selected = selector.transform(X_train)
X_test_selected = selector.transform(X_test)

# List of important features
important_features = X.columns[selector.get_support()]

print("Selected Features:\n", important_features)

In [ ]:
# Required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming your dataset is already preprocessed

# Splitting the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest Classifier
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Output the results
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)


In [ ]:
import numpy as np

def add_laplace_noise(data, epsilon):
    """
    Add Laplace noise to the predictions for differential privacy.
    Epsilon is the privacy budget parameter controlling the noise level.
    """
    noise = np.random.laplace(0, 1/epsilon, size=data.shape)
    noisy_data = data + noise
    return np.round(noisy_data)

epsilon = 0.1  # Privacy budget
y_pred_noisy = add_laplace_noise(y_pred, epsilon)

# Evaluate the model with noisy predictions
accuracy_noisy = accuracy_score(y_test, y_pred_noisy)
conf_matrix_noisy = confusion_matrix(y_test, y_pred_noisy)
class_report_noisy = classification_report(y_test, y_pred_noisy)

# Output the results
print(f"Accuracy with Differential Privacy: {accuracy_noisy * 100:.2f}%")
print("Confusion Matrix with Differential Privacy:")
print(conf_matrix_noisy)
print("Classification Report with Differential Privacy:")
print(class_report_noisy)

In [ ]:
X.columns

In [ ]:
# Generate the correlation matrix
correlation_matrix = X.corr()

# Display the correlation matrix
print(correlation_matrix)


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Set the figure size
plt.figure(figsize=(12, 8))

# Generate the heatmap with annotations
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)

# Set the title for the plot
plt.title('Correlation Matrix Heatmap')

# Show the plot
plt.show()


In [ ]:
X